lists/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^(\d+)/$', 'lists.views.view_list', name='view_list'),
    url(r'^new$','lists.views.new_list',name='new_list'),
)

superlists/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'lists.views.home_page', name='home'),
    url(r'^lists/', include('lists.urls')),
)

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse


class List(models.Model):

    def get_absolute_url(self):
        return reverse('view_list',args=[self.id])

class Item(models.Model):
    text = models.TextField(default='') #I guess .TextField() returns a method?
    list = models.ForeignKey(List, default=None)

lists/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.core.exceptions import ValidationError
from lists.models import Item, List
from lists.forms import ItemForm

def home_page(request):
    items = Item.objects.all()
    return render(request, 'home.html', {'form': ItemForm()}) 

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ItemForm()
    if request.method == 'POST':
        form = ItemForm(data=request.POST)
        if form.is_valid():
            form.save(for_list = list_)
            return redirect(list_)
    return render(request, 'list.html', {'list':list_,"form":form})

def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list = list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {"form":form})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>To-Do lists</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/base.css" rel="stylesheet" media="screen">
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 jumbotron">
                    <div class="text-center">
                        <h1> {% block header_text %}{% endblock %} </h1>
                        <form method="POST" action="{% block form_action %}{% endblock %}">
                            {{ form.text }}
                            {% csrf_token %}
                            {% if form.errors %}
                                <div class='form-group has-error'>
                                    <div class='help-block'>{{ form.text.errors }}</div>
                                </div>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    {% block table %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %} Your to-do list {% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}
        
{% block table %}
        <table id='id_list_table' class='table'> 
            {% for item in list.item_set.all %}
                <tr><td>{{ forloop.counter }}: {{ item.text }} </tr> </td>
            {% endfor %}
        </table>
{% endblock %}